Linear Regression Live coding

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from pandas_profiling import ProfileReport
from sklearn.linear_model import LinearRegression

In [12]:
df=pd.read_csv('Advertising.csv')
df

Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [13]:
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [14]:
corr=df.corr()

In [15]:
corr

Unnamed: 0        TV     Radio  Newspaper     Sales
Unnamed: 0    1.000000  0.017715 -0.110680  -0.154944 -0.051616
TV            0.017715  1.000000  0.054809   0.056648  0.782224
Radio        -0.110680  0.054809  1.000000   0.354104  0.576223
Newspaper    -0.154944  0.056648  0.354104   1.000000  0.228299
Sales        -0.051616  0.782224  0.576223   0.228299  1.000000

In [16]:
df.describe()

Unnamed: 0          TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [17]:
df=df.drop(df.columns[0],axis=1)

In [18]:
df.head(50)

TV  Radio  Newspaper  Sales
0   230.1   37.8       69.2   22.1
1    44.5   39.3       45.1   10.4
2    17.2   45.9       69.3    9.3
3   151.5   41.3       58.5   18.5
4   180.8   10.8       58.4   12.9
5     8.7   48.9       75.0    7.2
6    57.5   32.8       23.5   11.8
7   120.2   19.6       11.6   13.2
8     8.6    2.1        1.0    4.8
9   199.8    2.6       21.2   10.6
10   66.1    5.8       24.2    8.6
11  214.7   24.0        4.0   17.4
12   23.8   35.1       65.9    9.2
13   97.5    7.6        7.2    9.7
14  204.1   32.9       46.0   19.0
15  195.4   47.7       52.9   22.4
16   67.8   36.6      114.0   12.5
17  281.4   39.6       55.8   24.4
18   69.2   20.5       18.3   11.3
19  147.3   23.9       19.1   14.6
20  218.4   27.7       53.4   18.0
21  237.4    5.1       23.5   12.5
22   13.2   15.9       49.6    5.6
23  228.3   16.9       26.2   15.5
24   62.3   12.6       18.3    9.7
25  262.9    3.5       19.5   12.0
26  142.9   29.3       12.6   15.0
27  240.1   16.7       22.9   15.9
28  248.8   27.1       22.9   18.9
29   70.6   16.0       40.8   10.5
30  292.9   28.3       43.2   21.4
31  112.9   17.4       38.6   11.9
32   97.2    1.5       30.0    9.6
33  265.6   20.0        0.3   17.4
34   95.7    1.4        7.4    9.5
35  290.7    4.1        8.5   12.8
36  266.9   43.8        5.0   25.4
37   74.7   49.4       45.7   14.7
38   43.1   26.7       35.1   10.1
39  228.0   37.7       32.0   21.5
40  202.5   22.3       31.6   16.6
41  177.0   33.4       38.7   17.1
42  293.6   27.7        1.8   20.7
43  206.9    8.4       26.4   12.9
44   25.1   25.7       43.3    8.5
45  175.1   22.5       31.5   14.9
46   89.7    9.9       35.7   10.6
47  239.9   41.5       18.5   23.2
48  227.2   15.8       49.9   14.8
49   66.9   11.7       36.8    9.7

In [19]:
#pf=ProfileReport(df)
#pf.to_widgets()

we see that there is a good relationship between sales and tv and sales and radio.

In [20]:
pf.to_file('EDA.html')

NameError: name 'pf' is not defined

In [21]:
#Lets build a model

In [22]:
#select features and select label
#we can build a model betwen TV and Sale

In [23]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [24]:
x=df['TV']
x

0      230.1
1       44.5
2       17.2
3      151.5
4      180.8
       ...  
195     38.2
196     94.2
197    177.0
198    283.6
199    232.1
Name: TV, Length: 200, dtype: float64

In [25]:
y=df.Sales
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64

In [26]:
#Lets get the library
#for any code related enquiry always follow the official documentation.
# example: for sk learn search sklearn documentation

In [ ]:
#%matplotlib tk
plt.scatter(x,y)
plt.xlabel('TV')
plt.ylabel('Sales')
plt.show()

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train, y_test = train_test_split(x,y,test_size = 0.4, random_state = 23)

In [29]:
x_train

61     261.3
84     213.5
109    255.4
120    141.3
170     50.0
       ...  
91      28.6
31     112.9
182     56.2
40     202.5
83      68.4
Name: TV, Length: 120, dtype: float64

In [30]:
#now we need to convert this x_train, x_test and y_train and y_test to 2 dimensional data.
#we can do this using the numpy library
x_train = np.array(x_train).reshape(-1,1)
x_test = np.array(x_test).reshape(-1,1)
y_train = np.array(y_train).reshape(-1,1)
y_test = np.array(y_test).reshape(-1,1)

In [31]:
from sklearn.linear_model import LinearRegression

In [32]:
lr = LinearRegression()

In [33]:
lr.fit(x_train,y_train)

LinearRegression()

In [34]:
c = lr.intercept_
c

array([7.13286251])

In [35]:
m = lr.coef_
m

array([[0.04618986]])

In [36]:
y_pred_train=m*x_train + c
y_pred_train.flatten()

array([19.2022722 , 16.99439703, 18.92975204, 13.65948934,  9.44235537,
       17.56253227,  7.92732806, 12.72183524, 13.37773121,  7.4931434 ,
       15.67336711, 20.41706545,  7.16519541, 16.36159598, 10.26453483,
       17.47939053, 12.68488335,  7.53471427, 17.08215776,  8.88807709,
       17.28539313, 20.09835543, 12.20450883, 19.266938  , 11.2114269 ,
       16.2599783 , 13.61329948, 18.296951  ,  9.36383262, 10.74490935,
        7.67328384,  9.11902637, 11.55323185, 14.6756662 ,  8.89731506,
       18.1352865 , 19.40088859, 18.22304723, 16.05674293, 16.36159598,
        7.92732806, 18.72189769, 15.4839887 ,  9.12364536, 20.69420459,
       10.39386643,  8.28760894, 17.67800691, 17.96438403, 18.60642304,
       12.54631378, 10.58324485, 13.73339311, 15.30846724,  9.18831116,
       17.04982486, 17.40548676, 15.83503161,  8.31532286, 11.57632678,
       18.09833461, 11.4700901 , 18.85584827, 12.20450883, 16.68954397,
       18.18609534, 18.22304723,  8.58784301, 16.32926308, 10.66

In [37]:
#we can also predict using the predict function
y_pred_train1=lr.predict(x_train)
y_pred_train1.flatten()

array([19.2022722 , 16.99439703, 18.92975204, 13.65948934,  9.44235537,
       17.56253227,  7.92732806, 12.72183524, 13.37773121,  7.4931434 ,
       15.67336711, 20.41706545,  7.16519541, 16.36159598, 10.26453483,
       17.47939053, 12.68488335,  7.53471427, 17.08215776,  8.88807709,
       17.28539313, 20.09835543, 12.20450883, 19.266938  , 11.2114269 ,
       16.2599783 , 13.61329948, 18.296951  ,  9.36383262, 10.74490935,
        7.67328384,  9.11902637, 11.55323185, 14.6756662 ,  8.89731506,
       18.1352865 , 19.40088859, 18.22304723, 16.05674293, 16.36159598,
        7.92732806, 18.72189769, 15.4839887 ,  9.12364536, 20.69420459,
       10.39386643,  8.28760894, 17.67800691, 17.96438403, 18.60642304,
       12.54631378, 10.58324485, 13.73339311, 15.30846724,  9.18831116,
       17.04982486, 17.40548676, 15.83503161,  8.31532286, 11.57632678,
       18.09833461, 11.4700901 , 18.85584827, 12.20450883, 16.68954397,
       18.18609534, 18.22304723,  8.58784301, 16.32926308, 10.66

In [38]:
import matplotlib.pyplot as plt
#%matplotlib tk
plt.scatter(x_train,y_train)
plt.scatter(x_train, y_pred_train1,color = 'red')
plt.xlabel('TV')
plt.ylabel('sales')


Text(0, 0.5, 'sales')

In [39]:
#now lets try the model using x_test and y-test

In [40]:
y_pred_test1=lr.predict(x_test)
y_pred_test1.flatten()

array([ 8.37075069, 20.66187169, 20.34316168, 12.69874031, 16.56021237,
        8.02894574, 15.67336711, 13.93662848, 20.23230602, 17.40548676,
       16.60178324,  7.9134711 , 11.2760927 , 18.20919027, 10.62019673,
       17.85352837, 14.05210312, 10.01049062, 17.18839443, 10.52319803,
       19.92283397, 17.12834761, 14.68490417, 10.6617676 ,  7.52085731,
       20.82353619, 16.86968441, 15.8073177 , 11.77032418, 10.61095876,
       19.38241265, 10.32920063, 16.68492498, 11.3084256 , 16.07983785,
       20.0752605 ,  7.53009528, 14.73109402, 17.22072733, 13.50244382,
       18.21380926, 10.18601207,  8.03818371,  8.29222793, 17.30848806,
        7.95966096, 18.62489899, 17.14682356, 14.36619415, 16.81425658,
        7.73794964,  7.99661284, 13.18835279, 20.13068833, 13.10983004,
       13.21606671, 16.98977804, 16.2599783 ,  8.00123183, 16.32002511,
       13.57634759, 14.13062588, 20.26463892,  8.40308359, 19.77502643,
       12.24607971, 13.56710962, 10.83728906, 15.22070651, 16.86

In [41]:
%matplotlib tk
plt.scatter(x_test,y_test)
plt.scatter(x_test, y_pred_test1,color = 'red')
plt.xlabel('TV')
plt.ylabel('sales')

Text(0, 0.5, 'sales')

# Now Lets do this linear regression using gradient descent

In [ ]:
#Refer to "Machine learning tutorial python - 4: Gradient Descent and cost function"
# codebasic youtube channel
#also refer https://am207.github.io/2017/wiki/gradientdescent.html
#also refer https://raw.githubusercontent.com/mattnedrich/GradientDescenetExample/master/gradient_descent

In [42]:
import numpy as np

In [43]:
def gradient_descent(x,y):
    pass

In [44]:
x = np.array(df['TV'])
y = np.array(df['Sales'])

In [76]:
def gradient_descent(x,y):
    m_curr = c_curr = 0 #we have to start somewhere, so we start by assigning m, c to zero
    iteration = 40
    n=len(x)
    learning_rate = 0.1
    for i in range(iteration):
        y_predicted = m_curr*x + c_curr
        loss = (1/n)*sum([val**2 for val in (y-y_predicted)])
        #we need to calculate derivative of m and c to find slope 
        md = -(2/n)*sum(x*(y-y_predicted))
        cd = -(2/n)*sum(y-y_predicted)
        m_curr = m_curr-learning_rate*md
        c_curr = c_curr - learning_rate*cd
        print("m = {},   c = {},   loss = {},   iteration_number is {}".format(m_curr,c_curr,loss,i))
        
        

The equation of the best fit line is in this format y=mx+c
Now we need to find the slope(m) and y-intercept(c) of the best fit line by using gradient descent 

In [77]:
gradient_descent(x,y)

m = 482.10834,   c = 2.804500000000001,   loss = 223.71625000000003,   iteration_number is 0
m = -2791064.7332046228,   c = -14173.03501689,   loss = 6728176891.888895,   iteration_number is 1
m = 16161012529.217173,   c = 82069691.58293462,   loss = 2.2557693444321978e+17,   iteration_number is 2
m = -93576589392483.64,   c = -475205481209.4126,   loss = 7.562963093171159e+24,   iteration_number is 3
m = 5.418335061952932e+17,   c = 2751566964763891.5,   loss = 2.535649794596643e+32,   iteration_number is 4
m = -3.137361067996629e+21,   c = -1.5932309413372463e+19,   loss = 8.501323888045175e+39,   iteration_number is 5
m = 1.8166160561198714e+25,   c = 9.225233712064818e+22,   loss = 2.8502558990384575e+47,   iteration_number is 6
m = -1.0518693334394564e+29,   c = -5.341657309943154e+26,   loss = 9.55611008001673e+54,   iteration_number is 7
m = 6.09060506155384e+32,   c = 3.0929625966606315e+30,   loss = 3.203896179715096e+62,   iteration_number is 8
m = -3.5266233967035234e+36,   

In [ ]:
# where to stop.
#once you reach the global minima, your loss kind of stays the same. 
#so you need to select your learning rate and number of iterations accordingly 